# SPDX-License-Identifier: BSD-3-Clause
PORTNAME=       budyk
PORTVERSION=    0.1.0
CATEGORIES=     sysutils
MASTER_SITES=   # TODO: GH or release tarball

MAINTAINER=     # TODO
COMMENT=        Lightweight server monitoring with adaptive collection

LICENSE=        BSD3CLAUSE

USES=           cmake lua:5.4

CMAKE_ARGS=     -DSTATIC_LINK=ON -DENABLE_LLM=OFF

PLIST_FILES=    ${_PLIST_FILES}

.include <bsd.port.mk>
